name: release_scheduled
on:
  schedule:
    # Runs every Tuesday, at 1500 UTC.
    #
    # See: https://crontab.guru/#0_15_*_*_2
    - cron: '0 15 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          env: |
            GITHUB_ACTOR
            GITHUB_TOKEN
            GH_TOKEN
          runCmd: ./build-vitess-packages.sh
